{{- if .Values.build.enabled }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}    
spec:
  runPolicy: "Serial"
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"  
  source:
    git:
      uri: 'https://github.com/buuhsmead/rad-wheel.git'
      ref: "main"
        #    sourceSecret:
        #      name: git-source
  strategy:
    type: Docker
    dockerStrategy:
{{- if .Values.build.pullSecret }}
     pullSecret:
       name: {{ .Values.build.pullSecret }}
{{- end }}
      dockerfilePath: Dockerfile
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
{{- if .Values.build.resources }}
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
{{- end }}    
  triggers:
    - type: ConfigChange
{{- end }}

