  {{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-sa-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'
subjects:
  - kind: ServiceAccount
    name: {{ include "maven-template.serviceAccountName" . }}
  {{- end }}
