{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maven-template.serviceAccountName" . }}
  labels:
    {{- include "maven-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{/*  User "system:serviceaccount:freubel:probeer-sa" cannot get resource "builds"*/}}
{{/*  oc policy add-role-to-user edit system:serviceaccount:freubel:probeer-sa -n freubel*/}}
